[package]
name = "rust_snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.127.0"
rand = "0.8.4"
gfx = "*"
gfx_device_gl = "*"
timer = "0.2.0"
chrono = "0.4.23"
